# Generated by Django 3.2 on 2021-12-13 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('[A-Z]{2} \\d{4} [A-Z]{2}')]),
        ),
    ]
