# Generated by Django 3.2 on 2021-12-13 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0002_alter_vehicle_plate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
