# Generated by Django 3.2 on 2021-12-13 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0004_alter_driver_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('[А-Я]{2} \\d{4} [А-Я]{2}')]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
